import {MODULE_NAMESPACE} from './manifest';

export const SET_INIT_COMPLETED = `${MODULE_NAMESPACE}/SET_INIT_COMPLETED`;
export const SET_MENU_ITEMS = `${MODULE_NAMESPACE}/SET_MENU_ITEMS`;
export const RESET = `${MODULE_NAMESPACE}/RESET`;
