import {MODULE_NAMESPACE} from './manifest';

export const SET_INIT_COMPLETED = `${MODULE_NAMESPACE}/SET_INIT_COMPLETED`;
export const SET_ITEM_DETAILS = `${MODULE_NAMESPACE}/SET_ITEM_DETAILS`;
export const RESET = `${MODULE_NAMESPACE}/RESET`;