import {MODULE_NAMESPACE} from './manifest';

export const SET_INIT_COMPLETED = `${MODULE_NAMESPACE}/SET_INIT_COMPLETED`;
export const SET_CONTEXT = `${MODULE_NAMESPACE}/SET_CONTEXT`;
export const RESET = `${MODULE_NAMESPACE}/RESET`;
